# -*- coding: utf-8 -*-
"""irisklasifikasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xojL3dnmQpx3Lu0tJCIH8uut9pYDkZPA
"""

pip install streamlit

pip install scikit-learn

pip install pandas

app.py

Halaman
1
/
1
100%
import streamlit as st
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

st.title("🌸 Iris Flower Classification App")

# Load and cache data
@st.cache_data
def load_data():
    iris = load_iris()
    X = pd.DataFrame(iris.data, columns=iris.feature_names)
    y = pd.Series(iris.target)
    return X, y, iris.target_names

X, y, target_names = load_data()

# Train and cache model
@st.cache_resource
def train_model(X, y):
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model

model = train_model(X, y)

# Sidebar inputs
st.sidebar.header("Input Features")
sepal_length = st.sidebar.slider("Sepal length (cm)", float(X.iloc[:,0].min()), float(X.iloc[:,0].max()), float(X.iloc[:,0].mean()))
sepal_width  = st.sidebar.slider("Sepal width (cm)",  float(X.iloc[:,1].min()), float(X.iloc[:,1].max()), float(X.iloc[:,1].mean()))
petal_length = st.sidebar.slider("Petal length (cm)", float(X.iloc[:,2].min()), float(X.iloc[:,2].max()), float(X.iloc[:,2].mean()))
petal_width  = st.sidebar.slider("Petal width (cm)",  float(X.iloc[:,3].min()), float(X.iloc[:,3].max()), float(X.iloc[:,3].mean()))

input_data = pd.DataFrame([[sepal_length, sepal_width, petal_length, petal_width]], columns=X.columns)

# Predict
if st.button("Predict"):
    prediction = model.predict(input_data)[0]
    proba = model.predict_proba(input_data)[0]

    st.subheader("Prediction Result")
    st.success(f"🌼 Species: **{target_names[prediction]}**")

    st.subheader("Prediction Probabilities")
    st.bar_chart(pd.DataFrame(proba, index=target_names, columns=["Probability"]))
else:
    st.info("⬅️ Masukkan fitur dan klik Predict")

Menampilkan app.py.

import streamlit as st
import pandas as pd
import os
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

st.title("📨 SMS Spam Detection")

@st.cache_data
def load_data():
    df = pd.read_csv("SMSSpamCollection.txt", sep="\t", header=None, names=["label", "message"])
    return df

@st.cache_resource
def train_and_save_model(df):
    X = df['message']
    y = df['label'].map({'ham': 0, 'spam': 1})

    vectorizer = TfidfVectorizer()
    X_vec = vectorizer.fit_transform(X)

    model = MultinomialNB()
    model.fit(X_vec, y)

    # Save model & vectorizer
    joblib.dump(model, "model.pkl")
    joblib.dump(vectorizer, "vectorizer.pkl")

    return model, vectorizer

# Load or train model
if os.path.exists("model.pkl") and os.path.exists("vectorizer.pkl"):
    model = joblib.load("model.pkl")
    vectorizer = joblib.load("vectorizer.pkl")
else:
    df = load_data()
    model, vectorizer = train_and_save_model(df)

# User input
st.subheader("Cek apakah SMS termasuk spam:")
user_input = st.text_area("Masukkan pesan SMS:")

if st.button("Deteksi"):
    if user_input.strip() == "":
        st.warning("Tolong masukkan teks.")
    else:
        input_vec = vectorizer.transform([user_input])
        pred = model.predict(input_vec)[0]
        proba = model.predict_proba(input_vec)[0]

        label = "🚫 Spam" if pred == 1 else "✅ Bukan Spam"
        st.success(f"Hasil Deteksi: {label}")
        st.write(f"Probabilitas Spam: {proba[1]:.2f}")